# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Exam23Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExamWindow(object):
    def setupUi(self, ExamWindow):
        ExamWindow.setObjectName("ExamWindow")
        ExamWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        ExamWindow.resize(941, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExamWindow.sizePolicy().hasHeightForWidth())
        ExamWindow.setSizePolicy(sizePolicy)
        ExamWindow.setMinimumSize(QtCore.QSize(941, 494))
        ExamWindow.setMaximumSize(QtCore.QSize(941, 494))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./data/img/EGE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExamWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ExamWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QuestionsText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.QuestionsText.setGeometry(QtCore.QRect(10, 60, 921, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QuestionsText.setFont(font)
        self.QuestionsText.setObjectName("QuestionsText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(530, 450, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TimerLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TimerLabel.setFont(font)
        self.TimerLabel.setObjectName("TimerLabel")
        self.horizontalLayout.addWidget(self.TimerLabel)
        self.lcd_time = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcd_time.setObjectName("lcd_time")
        self.horizontalLayout.addWidget(self.lcd_time)
        self.horizontalLayout.setStretch(1, 2)
        self.ExamProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.ExamProgress.setGeometry(QtCore.QRect(10, 450, 161, 31))
        self.ExamProgress.setProperty("value", 0)
        self.ExamProgress.setObjectName("ExamProgress")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 340, 381, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnNext = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.BtnNext.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BtnNext.setFont(font)
        self.BtnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnNext.setStyleSheet("QPushButton {\n"
                                   "    border: 2px solid #8f8f91;\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
                                   "    min-width: 80px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "QPushButton:default {\n"
                                   "    border-color: navy; /* make the default button prominent */\n"
                                   "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../arrow_prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnNext.setIcon(icon)
        self.BtnNext.setIconSize(QtCore.QSize(50, 20))
        self.BtnNext.setAutoDefault(False)
        self.BtnNext.setDefault(True)
        self.BtnNext.setFlat(False)
        self.BtnNext.setObjectName("BtnNext")
        self.horizontalLayout_2.addWidget(self.BtnNext)
        self.BtnPrev = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnPrev.sizePolicy().hasHeightForWidth())
        self.BtnPrev.setSizePolicy(sizePolicy)
        self.BtnPrev.setMinimumSize(QtCore.QSize(84, 0))
        self.BtnPrev.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnPrev.setSizeIncrement(QtCore.QSize(0, 0))
        self.BtnPrev.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BtnPrev.setFont(font)
        self.BtnPrev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnPrev.setStyleSheet("QPushButton {\n"
                                   "    border: 2px solid #8f8f91;\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
                                   "    min-width: 80px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "QPushButton:default {\n"
                                   "    border-color: navy; /* make the default button prominent */\n"
                                   "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../arrow-blue-png-6-min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnPrev.setIcon(icon1)
        self.BtnPrev.setIconSize(QtCore.QSize(50, 20))
        self.BtnPrev.setDefault(True)
        self.BtnPrev.setObjectName("BtnPrev")
        self.horizontalLayout_2.addWidget(self.BtnPrev)
        self.BtnEnd = QtWidgets.QPushButton(self.centralwidget)
        self.BtnEnd.setGeometry(QtCore.QRect(740, 10, 186, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnEnd.sizePolicy().hasHeightForWidth())
        self.BtnEnd.setSizePolicy(sizePolicy)
        self.BtnEnd.setMinimumSize(QtCore.QSize(84, 0))
        self.BtnEnd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BtnEnd.setSizeIncrement(QtCore.QSize(0, 0))
        self.BtnEnd.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BtnEnd.setFont(font)
        self.BtnEnd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnEnd.setStyleSheet("QPushButton {\n"
                                  "    border: 2px solid #8f8f91;\n"
                                  "    border-radius: 6px;\n"
                                  "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                  "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
                                  "    min-width: 80px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                  "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                  "}\n"
                                  "\n"
                                  "\n"
                                  "\n"
                                  "QPushButton:default {\n"
                                  "    border-color: navy; /* make the default button prominent */\n"
                                  "}")
        self.BtnEnd.setIconSize(QtCore.QSize(50, 20))
        self.BtnEnd.setDefault(True)
        self.BtnEnd.setObjectName("BtnEnd")
        self.QuestionLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuestionLabel.setGeometry(QtCore.QRect(30, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QuestionLabel.setFont(font)
        self.QuestionLabel.setObjectName("QuestionLabel")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 340, 341, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.AnswerLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.AnswerLineEdit.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnswerLineEdit.setFont(font)
        self.AnswerLineEdit.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.AnswerLineEdit.setObjectName("AnswerLineEdit")
        self.horizontalLayout_3.addWidget(self.AnswerLineEdit)
        self.BtnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSave.sizePolicy().hasHeightForWidth())
        self.BtnSave.setSizePolicy(sizePolicy)
        self.BtnSave.setMinimumSize(QtCore.QSize(84, 0))
        self.BtnSave.setMaximumSize(QtCore.QSize(200, 40))
        self.BtnSave.setSizeIncrement(QtCore.QSize(0, 0))
        self.BtnSave.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BtnSave.setFont(font)
        self.BtnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnSave.setStyleSheet("QPushButton {\n"
                                   "    border: 2px solid #8f8f91;\n"
                                   "    border-radius: 6px;\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
                                   "    min-width: 80px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                   "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "QPushButton:default {\n"
                                   "    border-color: navy; /* make the default button prominent */\n"
                                   "}")
        self.BtnSave.setIconSize(QtCore.QSize(50, 20))
        self.BtnSave.setDefault(True)
        self.BtnSave.setObjectName("BtnSave")
        self.horizontalLayout_3.addWidget(self.BtnSave)
        ExamWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExamWindow)
        QtCore.QMetaObject.connectSlotsByName(ExamWindow)

    def retranslateUi(self, ExamWindow):
        _translate = QtCore.QCoreApplication.translate
        ExamWindow.setWindowTitle(_translate("ExamWindow", "Тестирование 23 задание ЕГЭ информатика"))
        self.TimerLabel.setText(_translate("ExamWindow", "Таймер тестирования:"))
        self.BtnNext.setText(_translate("ExamWindow", "Следующий"))
        self.BtnPrev.setText(_translate("ExamWindow", "Предыдущий"))
        self.BtnEnd.setText(_translate("ExamWindow", "Закончить тестирование"))
        self.QuestionLabel.setText(_translate("ExamWindow", "Вопрос №"))
        self.label_3.setText(_translate("ExamWindow", "Ответ"))
        self.BtnSave.setText(_translate("ExamWindow", "Сохранить"))
