# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserDialog(object):
    def setupUi(self, UserDialog):
        UserDialog.setObjectName("UserDialog")
        UserDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        UserDialog.resize(411, 224)
        UserDialog.setMinimumSize(QtCore.QSize(411, 224))
        UserDialog.setMaximumSize(QtCore.QSize(411, 224))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./data/img/EGE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserDialog.setWindowIcon(icon)
        UserDialog.setModal(True)
        self.user_name_edit = QtWidgets.QLineEdit(UserDialog)
        self.user_name_edit.setGeometry(QtCore.QRect(20, 140, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        font.setWeight(75)
        self.user_name_edit.setFont(font)
        self.user_name_edit.setObjectName("user_name_edit")
        self.label = QtWidgets.QLabel(UserDialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(UserDialog)
        self.buttonBox_2.setGeometry(QtCore.QRect(30, 180, 341, 32))
        self.buttonBox_2.setMinimumSize(QtCore.QSize(341, 32))
        self.buttonBox_2.setMaximumSize(QtCore.QSize(341, 32))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setCenterButtons(True)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.label_2 = QtWidgets.QLabel(UserDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        font.setWeight(75)
        self.users_combo = QtWidgets.QComboBox(UserDialog)
        self.users_combo.setGeometry(QtCore.QRect(20, 40, 371, 31))
        self.users_combo.setObjectName("users_combo")
        self.users_combo.setFont(font)
        self.label_3 = QtWidgets.QLabel(UserDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.retranslateUi(UserDialog)
        QtCore.QMetaObject.connectSlotsByName(UserDialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выбор пользователя"))
        self.label.setText(_translate("Dialog", "или создайте нового"))
        self.label_2.setText(_translate("Dialog", "Выберите пользователя"))
        self.label_3.setText(_translate("Dialog", "Представьтесь, пожалуйста"))
